name: rimu
version: 11.1.8

description: Rimu is a readable-text to HTML markup language inspired by AsciiDoc and Markdown.
homepage: https://srackham.github.io/rimu/
repository: https://github.com/srackham/rimu-dart/

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.17.11

executables:
  rimuc: