name: rimu
description: Rimu Markup for Dart.
version: 0.1.0
homepage: https://srackham.github.io/rimu/
repository: https://github.com/srackham/rimu-dart/
author: Stuart Rackham <srackham@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
