name: rimu
version: 11.1.5

description: Rimu is a readable-text to HTML markup language inspired by AsciiDoc and Markdown.
homepage: https://srackham.github.io/rimu/
repository: https://github.com/srackham/rimu-dart/

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
