name: rimu
version: 11.4.1

description: Rimu is a readable-text to HTML markup language inspired by AsciiDoc and Markdown.
homepage: https://srackham.github.io/rimu/
repository: https://github.com/srackham/rimu-dart/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.2
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  test: ^1.22.0

executables:
  rimuc: