name: Run Rimu tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # sdk: [stable]
        dart-version: [2.9.3]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Dart ${{ matrix.dart-version }}
        uses: cedx/setup-dart@v2
        with:
          release-channel: stable
          version: ${{ matrix.dart-version }}
      - name: Install package dependencies
        run: pub get
      - name: Run tests
        run: pub run test test/*.dart