name: Run Rimu tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dart-version: [2.10.0]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Dart ${{ matrix.dart-version }}
        uses: cedx/setup-dart@v2
        with:
          release-channel: stable
          version: ${{ matrix.dart-version }}
      - if: ${{ runner.os != 'Windows' }}
        env:
          rimucExe: 'build/rimuc'
      - if: ${{ runner.os == 'Windows' }}
        env:
          rimucExe: 'build/rimuc.exe'
      - name: Install package dependencies
        run: |
          pub get
      - name: Build rimuc executable
        run: |
          mkdir build
          dart2native bin/rimuc.dart -o ${{ env.rimucExe }}
      - name: Run tests
        run: |
          pub run test test/